- name: Initial setup
  hosts: all
  become: yes
  tasks:
    - name: Install dnf-automatic
      dnf:
        name: dnf-automatic
        state: present
    - name: Setup automatic updates in config
      replace:
        path: /etc/dnf/automatic.conf
        regexp: '^apply_updates\ =\ no$'
        replace: 'apply_updates = yes'
    - name: Enable automatic updates
      systemd:
        name: dnf-automatic.timer
        enabled: yes
        state: started
    - name: Setup hostnames
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      loop: "{{ groups.all }}"
